# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Desktop\BBDown_GUI\UI\qrcode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_QRcode(object):
    def setupUi(self, Form_QRcode):
        Form_QRcode.setObjectName("Form_QRcode")
        Form_QRcode.resize(455, 421)
        Form_QRcode.setMinimumSize(QtCore.QSize(455, 421))
        Form_QRcode.setMaximumSize(QtCore.QSize(455, 421))
        self.label_QR = QtWidgets.QLabel(Form_QRcode)
        self.label_QR.setGeometry(QtCore.QRect(80, 40, 300, 300))
        self.label_QR.setText("")
        self.label_QR.setObjectName("label_QR")
        self.label = QtWidgets.QLabel(Form_QRcode)
        self.label.setGeometry(QtCore.QRect(80, 370, 291, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form_QRcode)
        QtCore.QMetaObject.connectSlotsByName(Form_QRcode)

    def retranslateUi(self, Form_QRcode):
        _translate = QtCore.QCoreApplication.translate
        Form_QRcode.setWindowTitle(_translate("Form_QRcode", "二维码登录"))
        self.label.setText(_translate("Form_QRcode", "获取二维码中"))
