name: Build (dev)

on:
  push:
    branches: [ "dev*" ]
  pull_request:
    branches: [ "dev*" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv .venv
        .venv/Scripts/activate
        pip install -r requirements.txt
        pip install pyinstaller
    - name: build py to exe
      run: |
        .venv/Scripts/activate
        pyinstaller --noconfirm --onefile --noconsole --icon "./BBDown_GUI/UI/favicon.ico" --add-data "./BBDown_GUI/UI/favicon.ico;./UI"  "./build-to-exe.py"
    - name: Collect build file
      run: |
        cd dist
        mv build-to-exe.exe BBDown_GUI.exe
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: BBDown_GUI_single_file
        path: dist
