name: Build (dev)

on:
  push:
    branches: [ "dev*" ]
  pull_request:
    branches: [ "dev*" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update BBDown_GUI version
      run: |
        $version = $env:GITHUB_REF_NAME
        Write-Host BBDown_GUI-Version: $version

        # Replace BBDown_GUI version in ui_about.py
        $filePath = "./BBDown_GUI/UI/ui_about.py"
        (Get-Content $filePath) | Foreach-Object {$_ -replace '\$bbdown-gui-version\$', "$version"} | Set-Content $filePath

    - name: Update ffmpeg version
      run: |
        # Get latest ffmpeg version and website
        $url = "https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/latest"
        $response = Invoke-WebRequest -Uri $url | ConvertFrom-Json
        $version = $response.name
        $tag = $version
        $tag = $tag.Replace("Latest Auto-Build (", "autobuild-")
        $tag = $tag.Replace(" ", "-")
        $tag = $tag.Replace(":", "-")
        $tag = $tag.Replace(")", "")
        $website = "https://github.com/BtbN/FFmpeg-Builds/releases/tag/$tag"
        Write-Host FFmpeg-Version: $version
        Write-Host FFmpeg-Version-Website: $website

        # Replace ffmpeg version in ui_about.py
        $filePath = "./BBDown_GUI/UI/ui_about.py"
        (Get-Content $filePath) | Foreach-Object {$_ -replace '\$ffmpeg-version\$', "$version"} | Set-Content $filePath
        (Get-Content $filePath) | Foreach-Object {$_ -replace '\$ffmpeg-version-url\$', "$website"} | Set-Content $filePath

    - name: Update BBDown version
      run: |
        # Get latest BBDown version and website
        $url = "https://api.github.com/repos/nilaoda/BBDown/releases/latest"
        $response = Invoke-WebRequest -Uri $url | ConvertFrom-Json
        $version = $response.name
        $website = $response.html_url
        Write-Host BBDown-Version: $version
        Write-Host BBDown-Version-Website: $website

        # Replace BBDown version in ui_about.py
        $filePath = "./BBDown_GUI/UI/ui_about.py"
        (Get-Content $filePath) | Foreach-Object {$_ -replace '\$bbdown-version\$', "$version"} | Set-Content $filePath
        (Get-Content $filePath) | Foreach-Object {$_ -replace '\$bbdown-version-url\$', "$website"} | Set-Content $filePath

    - name: Update aria2 version
      run: |
        # Get latest aria2 version and website
        $url = "https://api.github.com/repos/aria2/aria2/releases/latest"
        $response = Invoke-WebRequest -Uri $url | ConvertFrom-Json
        $version = $response.name
        $website = $response.html_url
        Write-Host Aria2-Version: $version
        Write-Host Aria2-Version-Website: $website

        # Replace aria2 version in ui_about.py
        $filePath = "./BBDown_GUI/UI/ui_about.py"
        (Get-Content $filePath) | Foreach-Object {$_ -replace '\$aria2c-version\$', "$version"} | Set-Content $filePath
        (Get-Content $filePath) | Foreach-Object {$_ -replace '\$aria2c-version-url\$', "$website"} | Set-Content $filePath

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv .venv
        .venv/Scripts/activate
        pip install -r requirements.txt
        pip install pyinstaller
    - name: build py to exe
      run: |
        .venv/Scripts/activate
        pyinstaller --noconfirm --onefile --noconsole --icon "./BBDown_GUI/UI/favicon.ico" --add-data "./BBDown_GUI/UI/favicon.ico;./UI"  "./build-to-exe.py"
    - name: Collect build file
      run: |
        cd dist
        mv build-to-exe.exe BBDown_GUI.exe
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: BBDown_GUI_single_file
        path: dist
